trigger:
  - master

stages:
  - stage: Stage1
    displayName: First stage
    jobs:
      - job: Job1
        displayName: First job in first stage
        pool:
          vmImage: windows-latest
        steps:
          - script: echo Hello, world!
            displayName: 'First step: Run a one-line script'
          - script: |
              echo Add other tasks to build, test, and deploy your project.
              echo See https://aka.ms/yaml
            displayName: 'Second step: Run a multi-line script'

      - job: Job2
        displayName: Second job in first stage
        pool:
          vmImage: windows-latest
        steps:
          - script: echo Hello, world!
            displayName: 'First step: Run a one-line script'
          - script: |
              echo Add other tasks to build, test, and deploy your project.
              echo See https://aka.ms/yaml
            displayName: 'Second step: Run a multi-line script'

  - stage: Stage2
    displayName: Second stage
    jobs:
      - job: Job1
        displayName: First job in second stage
        pool:
          vmImage: windows-latest
        steps:
          - script: echo Hello, world!
            displayName: 'First step: Run a one-line script'
          - script: |
              echo Add other tasks to build, test, and deploy your project.
              echo See https://aka.ms/yaml
            displayName: 'Second step: Run a multi-line script'

      - job: Job2
        displayName: Second job in second stage
        pool:
          vmImage: windows-latest
        steps:
          - script: echo Hello, world!
            displayName: 'First step: Run a one-line script'
          - script: |
              echo Add other tasks to build, test, and deploy your project.
              echo See https://aka.ms/yaml
            displayName: 'Second step: Run a multi-line script'

  - stage: TerraformValidate
    displayName: Terraform validation
    dependsOn: VerifyCode
    jobs:
      - job: Terraform
        displayName: Terraform validate
        pool:
          vmImage: windows-latest
        steps:
          - checkout: self
          - task: TerraformInstaller@1
            displayName: Install Terraform
            inputs:
              terraformVersion: '1.6.6'
          - script: |
              cd terraform
              terraform init -backend=false
              terraform validate
            displayName: Terraform init & validate